package spec

import "strings"

// ---------------------------------------------------------------------------
// Deterministic markdown projection of the structured YAML model (change 007,
// Milestone 3 — design D3/D5; constitution ADR-0005).
//
// This is the structured-model counterpart to the markdown engine's
// RequirementSet.Render (render.go). It emits a byte-stable, READ-ONLY
// markdown projection of a LivingSpec (the owned YAML source of truth),
// carrying a derived kebab-slug marker for every requirement and every
// scenario.
//
// It is ADDED alongside RequirementSet.Render rather than replacing it: the
// markdown Render is still consumed by internal/guard (retargeted in M4) and
// internal/archive (retargeted in M8), per the orchestrator-approved additive
// strategy recorded as M2-DEV-001 / M3-DEV-001 ("the markdown engine is left
// intact for M3/M4/M8"). The projection is one-way — markdown is derived from
// the YAML and never parsed back — so, unlike the markdown Render, it carries
// no byte-fidelity round-trip contract (D3/D5).
// ---------------------------------------------------------------------------

// projectionHeader is the managed "generated / read-only, do not hand-edit"
// marker every projection carries as its first line (design D3), mirroring the
// scaffold managed-block marker style (internal/scaffold/block.go). The
// markdown is a deterministic read-only projection of spec.yaml; editing it by
// hand is meaningless because the next render overwrites it.
const projectionHeader = "<!-- GENERATED by spec-lifecycle from spec.yaml — read-only projection, do not hand-edit. -->"

// Slug derives the D5 kebab-slug from a requirement or scenario name:
// lowercase the input, collapse each maximal run of characters outside
// [a-z0-9] to a single "-", then trim any leading/trailing "-". The slug is
// derived at render time and never stored in the source (a stored slug would
// be a second source of truth that can drift — design D1/D5).
func Slug(name string) string {
	lower := strings.ToLower(name)
	var b strings.Builder
	b.Grow(len(lower))
	inDash := false
	for _, r := range lower {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			inDash = false
			continue
		}
		// Any character outside [a-z0-9] contributes to a separator run;
		// emit a single '-' for the whole maximal run.
		if !inDash {
			b.WriteByte('-')
			inDash = true
		}
	}
	return strings.Trim(b.String(), "-")
}

// RenderProjection renders the living spec to its deterministic, read-only
// markdown projection (design D3/D5). The output obeys the D5 byte-stability
// rules so "the same YAML always renders byte-identical markdown" (spec-format
// scenario) and the from-empty replay compare is exact:
//
//   - fixed section/key order: managed header → title → purpose → requirements
//     in source order → each requirement's scenarios in source order;
//   - a derived kebab-slug marker for every requirement and every scenario;
//   - LF line endings, no trailing whitespace on any line, a single trailing
//     newline.
//
// Rendering is a pure function of the model: it reads no clock, no filesystem,
// and no map iteration order (Requirements/Scenarios are sequences), so two
// renders of the same LivingSpec are byte-identical.
func (ls *LivingSpec) RenderProjection() []byte {
	var lines []string
	emit := func(s string) { lines = append(lines, s) }

	emit(projectionHeader)
	emit("")
	emit("# " + ls.Capability + " Specification")

	if strings.TrimSpace(ls.Purpose) != "" {
		emit("")
		emit("## Purpose")
		emit("")
		emitBlock(&lines, ls.Purpose)
	}

	emit("")
	emit("## Requirements")

	for _, r := range ls.Requirements {
		emit("")
		emit("### Requirement: " + r.Name)
		emit("<!-- slug: " + Slug(r.Name) + " -->")
		if strings.TrimSpace(r.Text) != "" {
			emit("")
			emitBlock(&lines, r.Text)
		}
		for _, sc := range r.Scenarios {
			emit("")
			emit("#### Scenario: " + sc.Name)
			emit("<!-- slug: " + Slug(sc.Name) + " -->")
			if len(sc.Given)+len(sc.When)+len(sc.Then) > 0 {
				emit("")
				for _, g := range sc.Given {
					emit("- **GIVEN** " + g)
				}
				for _, w := range sc.When {
					emit("- **WHEN** " + w)
				}
				for _, t := range sc.Then {
					emit("- **THEN** " + t)
				}
			}
		}
	}

	// D5 byte-stability normalization: strip trailing whitespace from every
	// line (block scalars may carry it), join with LF, collapse to a single
	// trailing newline.
	for i := range lines {
		lines[i] = strings.TrimRight(lines[i], " \t")
	}
	out := strings.TrimRight(strings.Join(lines, "\n"), "\n") + "\n"
	return []byte(out)
}

// emitBlock appends a multi-line body (purpose or requirement text) line by
// line, so a YAML block scalar spanning several lines projects with each of
// its lines as its own markdown line (trailing whitespace is stripped in the
// final normalization pass).
func emitBlock(lines *[]string, body string) {
	*lines = append(*lines, strings.Split(strings.TrimRight(body, "\n"), "\n")...)
}
